using Lexio.SharedKernel.Domain;

namespace Lexio.Architecture.Tests;

/// <summary>
/// Architecture invariants for the SharedKernel domain assembly.
/// Service-level domain layer rules are enforced in per-service architecture tests
/// generated by the Lexio.ServiceTemplate (phase 08).
/// </summary>
public sealed class DomainLayerTests
{
    private static readonly Types SharedKernelTypes =
        Types.InAssembly(typeof(AggregateRoot<>).Assembly);

    [Fact]
    public void SharedKernel_ShouldNot_DependOn_AspNetCore()
    {
        SharedKernelTypes
            .That().HaveNameStartingWith("Lexio")
            .ShouldNot().HaveDependencyOn("Microsoft.AspNetCore")
            .GetResult()
            .IsSuccessful
            .Should().BeTrue(because: "SharedKernel must not depend on AspNetCore");
    }

    [Fact]
    public void SharedKernel_ShouldNot_DependOn_EntityFrameworkCore()
    {
        SharedKernelTypes
            .That().HaveNameStartingWith("Lexio")
            .ShouldNot().HaveDependencyOn("Microsoft.EntityFrameworkCore")
            .GetResult()
            .IsSuccessful
            .Should().BeTrue(because: "SharedKernel must not depend on EF Core");
    }

    [Fact]
    public void SharedKernel_ShouldNot_DependOn_MassTransit()
    {
        SharedKernelTypes
            .That().HaveNameStartingWith("Lexio")
            .ShouldNot().HaveDependencyOn("MassTransit")
            .GetResult()
            .IsSuccessful
            .Should().BeTrue(because: "SharedKernel must not depend on MassTransit");
    }

    [Fact]
    public void SharedKernel_ShouldNot_DependOn_Mediator()
    {
        SharedKernelTypes
            .That().HaveNameStartingWith("Lexio")
            .ShouldNot().HaveDependencyOn("Mediator")
            .GetResult()
            .IsSuccessful
            .Should().BeTrue(because: "SharedKernel must not depend on Mediator");
    }
}
