namespace Lexio.Service1.Application.Common.Behaviors;

// TODO: Implement ValidationBehavior when Mediator pipeline is wired.
// Reference: https://github.com/martinothamar/Mediator#pipeline-behaviors
// This file is a placeholder generated by the Lexio service template.
// ReSharper disable once CheckNamespace
internal static class ValidationBehaviorPlaceholder { }
